import { gql } from "@apollo/client";

export const COUPONS = gql`
  query($name: String){
    coupons(name: $name){
      edges{
        node{
          id
          isDeleted
          deletedOn
          createdOn
          updatedOn
          name
          promoType
          maxUsesLimit
          maxLimitPerUser
          value
          minAmount
          maxAmount
          isActive
          startDate
          endDate
          addedFor{
            edges{
              node{
                id
                name
                email
                postCode
                contact
                isBlocked
                
              }
            }
          }
        }
      }
    }
}
`

export const COUPON = gql`
  query($id:ID){
  coupon(id:$id){
    id
    createdOn
    isDeleted
    name
    promoType
    maxUsesLimit
    maxLimitPerUser
    value
    minAmount
    maxAmount
    isActive
    startDate
    endDate
    usercouponSet{
      edges{
        node{
          id
          createdOn
          discountedAmount
          isPaymentSuccess
          user{
            id
            username
            email
            firstName
            lastName
          }
          coupon{
            id
            name
          }
        }
      }
    }
    addedFor{
      edges{
        node{
          id
          createdOn
          isDeleted
          name
          email
          logoUrl
        }
      }
    }
  }
}
`