import { gql } from "@apollo/client";

export const ORDER_PAYMENTS = gql`
  query($companyNameEmail: String, $status: String){
  orderPayments(companyNameEmail: $companyNameEmail, status: $status){
    edges{
      node{
        id
        createdOn
        paymentInfo
        paidAmount
        paymentType
        status
        paymentFor{
          id
          username
          email
          firstName
          lastName
      }
        company{
        id
        name
        email
        contact
        postCode
        isBlocked
        status
        logoUrl
        isDeleted
      }
      }
    }
  }
}
`

export const ORDER_PAYMENT = gql`
  query($id: ID){
  orderPayment(id:$id){
    id
    createdOn
    isDeleted
    paymentType
    paidAmount
    paymentInfo
    status
    note
    paymentFor{
      id
      isDeleted
      username
      email
      phone
      photoUrl
      firstName
      lastName
      postCode
      role
      vendor{
        id
        name
        email
      }
    }
    company{
      id
      name
      logoUrl
      email
      contact
      postCode
    }
    orders{
      edges{
        node{
          id
          createdOn
          isDeleted
          note
          paymentType
          deliveryDate
          companyAllowance
          finalPrice
          status
          dueAmount
          coupon{
            id
            name
          }
          orderCarts{
            edges{
              node{
                id
                createdOn
                isDeleted
                date
                cancelled
                priceWithTax
                totalPriceWithTax
                orderedQuantity
                dueAmount
                vendor{
                  id
                  name
                  email
                }
                item{
                  id
                  createdOn
                  priceWithTax
                  name
                  title
                  attachments{
                    edges{
                      node{
                        fileUrl
                        isCover
                      }
                    }
                  }
                  category{
                    id
                    name
                  }
                }
              }
            }
          }
          billingAddress{
            id
            firstName
            lastName
            address
            sector
            phone
          }
          shippingAddress{
            id
            addressType
            address
            postCode
            city
            fullName
            phone
            instruction
          }
        }
      }
    }
  }
}
`

export const USERS = gql`
  query($company: String){
  users(company:$company){
    edges{
      node{
        id
        username
        email
        firstName
        lastName
        photoUrl
        dueAmount
      }
    }
  }
}
`