import { gql } from "@apollo/client";

export const ORDERS = gql`
  query($companyNameEmail: String, $status: String){
    orders(companyNameEmail: $companyNameEmail, status: $status){
      edges{
        node{
          id
          createdOn
          isDeleted
          deletedOn
          finalPrice
          status
          deliveryDate
          finalPrice
          paidAmount
          coupon{
            id
            name
            isActive
            value
          }
          company{
            id
            name
            email
            contact
            postCode
            isBlocked
            status
            logoUrl
            orderedAmount
            invoiceAmount
            paidAmount
            balance
          }
          orderCarts{
            edges{
              node{
                id
                quantity
                priceWithTax
                totalPriceWithTax
                orderedQuantity
                item{
                  id
                  priceWithTax
                  name
                  attachments{
                  edges{
                    node{
                      fileUrl
                      isCover
                    }
                  }
                }
                }
              }
            }
          }
        }
      }
    }
}
`

export const ORDER = gql`
  query($id:ID!) {
    order(id:$id){
    id
    createdOn
    isDeleted
    deliveryDate
    finalPrice
    status
    createdOn
    isDeleted
    paymentType
    companyAllowance
    shippingCharge
    dueAmount
    discountAmount
    paidAmount
    isFullPaid
    coupon{
      id
      name
      isActive
      value
    }
    billingAddress{
      id
      firstName
      lastName
      address
      sector
      country
      phone
    }
    shippingAddress{
      id
      address
      postCode
      city
      state
      fullName
      phone
      instruction
    }
    company{
      id
      name
      email
      contact
      postCode
      allowancePercentage
      isBlocked
      status
      logoUrl
      noOfEmployees
      orderedAmount
      invoiceAmount
      paidAmount
    }
    orderCarts{
      edges{
        node{
          id
          cancelled
          orderedQuantity
          priceWithTax
          totalPriceWithTax
          ingredients{
          edges{
            node{
              id
              name
            }
          }
        }
          item{
            id
            priceWithTax
            name
            ingredients(isDeleted: false){
              edges{
                node{
                  id
                  name
                }
              }
            }
            attachments{
              edges{
                node{
                  id
                  fileUrl
                  isCover
                }
              }
            }
            category{
              id
              name
            }
            vendor{
              id
              name
              email
              contact
              postCode
              isBlocked
              logoUrl
            }
          }
          users{
            edges{
              node{
                id
                addedFor{
                  id
                  username
                  email
                  firstName
                  lastName
                  postCode
                  photoUrl
                  role
                  isDeleted
                  phone
                  dueAmount
                }
              }
            }
          }
        }
      }
    }
  }
  }
`