import { gql } from "@apollo/client";

export const COMPANY = gql`
  query($id: ID){
  company(id:$id){
    id
    name
    createdOn
    description
    email
    contact
    postCode
    logoUrl
    totalEmployee
    paidAmount
    orderedAmount
    balance
    isBlocked
    orders{
      edges{
        node{
          id
          createdOn
          coupon{
            id
            name
          }
          isDeleted
          paymentType
          deliveryDate
          companyAllowance
          discountAmount
          finalPrice
          paidAmount
          isFullPaid
          status
          dueAmount
        }
      }
    }
    owner{
      id
      username
      email
      firstName
      lastName
      phone
      photoUrl
      gender
      jobTitle
      dateOfBirth
      dateJoined
      address
    }
    users{
      edges{
        node{
          id
          createdOn
          isDeleted
          username
          email
          firstName
          lastName
          phone
          gender
          dateOfBirth
          address
          photoUrl
          dueAmount
          role
          allergies{
            edges{
              node{
                id
                name
              }
            }
          }
        }
      }
    }
  }
}
`

export const USER = gql`
  query User($id: ID){
    user(id: $id){
      id
      createdOn
      isDeleted
      username
      email
      phone
      photoUrl
      firstName
      lastName
      dateJoined
      dateOfBirth
      gender
      postCode
      jobTitle
      address
      about
      dueAmount
      allergies{
        edges{
          node{
            id
            name
          }
        }
      }
      company{
        id
        name
        email
      }
    }
  }
`