import { gql } from "@apollo/client";

export const ME = gql`
  query{
    me{
      id
      email
      firstName
      lastName
      username
      phone
      postCode
      gender
      role
      jobTitle
      dateOfBirth
      address
      about
      photoUrl
      fileId
      isActive
      company{
        id
        name
        email
        postCode
        logoUrl
        totalEmployee
        noOfEmployees
        description
        workingEmail
        contact
        isBlocked
        fileId
        balance
        formationDate
          billingAddress{
          id
          firstName
          lastName
          address
          sector
          country
          phone
        }
      }
      allergies{
        edges{
          node{
            id
            name
          }
        }
      }
    }
  }
`

export const GET_ALL_CATEGORY = gql`
query{
  categories{
  edges{
    node{
      id
      name
      description
      products{
        edges{
          node{
            id
            actualPrice
            name
            description
            attachments(isCover:true){
              edges{
                node{
                  id
                  fileUrl
                }
              }
            }
          }
        }
      }
    }
  }
}
}
`

export const GET_INGREDIENTS = gql`
  query{
    ingredients{
      edges{
        node{
          id
          name
          isActive
      }
    }
  }
}
`

export const CHECk_POST_CODE = gql`
  query CheckPostCode ($postCode: Int){
    checkPostCode(postCode: $postCode)
  }
`

export const COMPANIES = gql`
  query($nameEmail: String, $status: String){
  companies(nameEmail: $nameEmail, status: $status){
    edges{
      node{
        id
        isDeleted
        isBlocked
        isChecked
        name
        description
        email
        contact
        workingEmail
        postCode
        allowancePercentage
        noOfEmployees
        formationDate
        orderedAmount
        balance
        invoiceAmount
        logoUrl
        fileId
        paidAmount
        isValid
       totalEmployee
       owner{
          id
          username
          email
          firstName
          lastName
          photoUrl
        }
       users{
          edges{
            node{
              id
              username
              email
              firstName
              isVerified
              isActive
              isStaff
              phone
              postCode
              gender
              role
              photoUrl
              allergies{
                edges{
                  node{
                    id
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
`
